{% set name = "libseccomp" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/seccomp/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83b6085232d1588c379dc9b9cae47bb37407cf262e6e74993c61ba72d2a784dc
  patches:
    - patches/setup.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - automake
    - autoconf
    - libtool
    - gperf
    - make

outputs:
  - name: libseccomp
    script: install_lib.sh
    build:
      run_exports:
        # Has followed semver since 1.0.1 in 2012
        # https://abi-laboratory.pro/index.php?view=timeline&l=libseccomp
        - {{ pin_subpackage('libseccomp') }}
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - make
        - gperf
    test:
      commands:
        - test -f $PREFIX/lib/libseccomp.so
        - test ! -f $PREFIX/lib/libseccomp.a
  - name: seccomp
    script: install_python.sh
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
      host:
        - pip
        - python
        - cython
        - {{ pin_subpackage('libseccomp', exact=True) }}
      run:
        - {{ pin_subpackage('libseccomp', exact=True) }}
        - python
    test:
      imports:
        - seccomp

about:
  home: https://github.com/seccomp/libseccomp
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'libseccomp provides an easy to use, platform independent, interface to the Linux syscall filtering mechanism.'

  description: |
    The libseccomp library provides an easy to use, platform independent, 
    interface to the Linux Kernel's syscall filtering mechanism. The 
    libseccomp API is designed to abstract away the underlying BPF based 
    syscall filter language and present a more conventional function-call
    based filtering interface that should be familiar to, and easily 
    adopted by, application developers.
  dev_url: https://github.com/seccomp/libseccomp
  doc_url: https://github.com/seccomp/libseccomp

extra:
  recipe-maintainers:
    - mbargull
    - sodre
